version: '3'

services:
  studydb:
    image: postgres:13.1
    ports:
      - 5457:5432
    environment:
      - POSTGRES_PASSWORD=studypass
      - POSTGRES_USER=study
      - POSTGRES_DB=studydb
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=scram-sha-256
    command: postgres -c max_connections=50 -c log_min_messages=LOG
